version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: '{{ project_name }}'
      POSTGRES_PASSWORD: '{{ secret_key|slugify }}'

  cache:
    image: redis

  assets:
    build:
      dockerfile: docker/development/Dockerfile.assets
      context: .
    volumes:
      - ./project/assets:/app/project/assets/
    command: npm run watch

  master:
    build:
      context: ./salt/master
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:4505:4505
      - 0.0.0.0:4506:4506
    restart: always
    hostname: salt
    privileged: true
    environment:
        SALT_ROLE: master
    expose:
        - "4505"
        - "4506"
    volumes:
        - ./srv:/srv:rw
        - ./salt/salt:/srv/salt
        - ./salt/pillar:/srv/pillar

  minion1-dev:
     build:
       context: ./salt/minion
       dockerfile: Dockerfile
     container_name: project-mgr-dev
     hostname: project-mgr-dev
     environment:
         SALT_ROLE: minion
         SALT_GRAINS: "{'component': 'mgr'}"
     links:
         - master:1

  minion2-dev:
     build:
       context: ./salt/minion
       dockerfile: Dockerfile
     container_name: project-worker-dev
     hostname: project-worker-dev
     environment:
         SALT_ROLE: minion
         SALT_GRAINS: "{'component': 'worker'}"
     links:
         - master

  minion1-sta:
     build:
         context: ./salt/minion
         dockerfile: Dockerfile
     container_name: project-mgr-sta
     hostname: project-mgr-sta
     environment:
         SALT_ROLE: minion
         SALT_GRAINS: "{'component': 'mgr'}"
     links:
         - master

  minion2-sta:
     build:
         context: ./salt/minion
         dockerfile: Dockerfile
     container_name: project-worker-sta
     hostname: project-worker-sta
     environment:
         SALT_ROLE: minion
         SALT_GRAINS: "{'component': 'worker'}"
     links:
         - master
